checksumBehavior: update

nodeLinker: node-modules

packageExtensions:
  "@types/react-beautiful-dnd@*":
    peerDependencies:
      "@types/react": "*"
  "@types/react-dom@*":
    peerDependencies:
      "@types/react": "*"
  "@types/react-redux@*":
    peerDependencies:
      "@types/react": "*"
  "@types/react-transition-group@*":
    peerDependencies:
      "@types/react": "*"
  react-dev-utils@*:
    peerDependencies:
      react-error-overlay: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-3.2.1.cjs
