/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/javascripts/**/*.tsx'],
  theme: {
    extend: {
      zIndex: {
        'editor-content': 'var(--z-index-editor-content)',
        'editor-title-bar': 'var(--z-index-editor-title-bar)',
        'resizer-overlay': 'var(--z-index-resizer-overlay)',
        'component-view': 'var(--z-index-component-view)',
        'panel-resizer': 'var(--z-index-panel-resizer)',
        'dropdown-menu': 'var(--z-index-dropdown-menu)',
        'footer-bar': 'var(--z-index-footer-bar)',
        'footer-bar-item': 'var(--z-index-footer-bar-item)',
        'footer-bar-item-panel': 'var(--z-index-footer-bar-item-panel)',
        preferences: 'var(--z-index-preferences)',
        'purchase-flow': 'var(--z-index-purchase-flow)',
        'lock-screen': 'var(--z-index-lock-screen)',
        modal: 'var(--z-index-modal)',
      },
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      neutral: 'var(--sn-stylekit-neutral-color)',
      'neutral-contrast': 'var(--sn-stylekit-neutral-contrast-color)',
      info: 'var(--sn-stylekit-info-color)',
      'info-darkened': 'var(--sn-stylekit-info-color-darkened)',
      'info-contrast': 'var(--sn-stylekit-info-contrast-color)',
      'info-backdrop': 'var(--sn-stylekit-info-backdrop-color)',
      success: 'var(--sn-stylekit-success-color)',
      'success-contrast': 'var(--sn-stylekit-success-contrast-color)',
      warning: 'var(--sn-stylekit-warning-color)',
      'warning-contrast': 'var(--sn-stylekit-warning-contrast-color)',
      danger: 'var(--sn-stylekit-danger-color)',
      'danger-contrast': 'var(--sn-stylekit-danger-contrast-color)',
      default: 'var(--sn-stylekit-background-color)',
      foreground: 'var(--sn-stylekit-foreground-color)',
      contrast: 'var(--sn-stylekit-contrast-background-color)',
      text: 'var(--sn-stylekit-contrast-foreground-color)',
      border: 'var(--sn-stylekit-border-color)',
      'passive-0': 'var(--sn-stylekit-passive-color-0)',
      'passive-1': 'var(--sn-stylekit-passive-color-1)',
      'passive-2': 'var(--sn-stylekit-passive-color-2)',
      'passive-3': 'var(--sn-stylekit-passive-color-3)',
      'passive-4': 'var(--sn-stylekit-passive-color-4)',
      'passive-4-opacity-variant': 'var(--sn-stylekit-passive-color-4-opacity-variant)',
      'passive-5': 'var(--sn-stylekit-passive-color-5)',
      'passive-6': 'var(--sn-stylekit-passive-color-6)',
      'passive-super-light': 'var(--sn-stylekit-passive-color-super-light)',
      'accessory-tint-1': 'var(--sn-stylekit-accessory-tint-color-1)',
      'accessory-tint-2': 'var(--sn-stylekit-accessory-tint-color-2)',
      'accessory-tint-3': 'var(--sn-stylekit-accessory-tint-color-3)',
      'accessory-tint-4': 'var(--sn-stylekit-accessory-tint-color-4)',
      'accessory-tint-5': 'var(--sn-stylekit-accessory-tint-color-5)',
      'accessory-tint-6': 'var(--sn-stylekit-accessory-tint-color-6)',
    },
  },
  plugins: [],
}
