export enum PreferencePaneId {
  General = 'general',
  Account = 'account',
  Security = 'security',
  HomeServer = 'home-server',
  Vaults = 'vaults',
  Appearance = 'appearance',
  Backups = 'backups',
  Listed = 'listed',
  Plugins = 'plugins',
  Shortcuts = 'shortcuts',
  Accessibility = 'accessibility',
  GetFreeMonth = 'get-free-month',
  HelpFeedback = 'help-feedback',
  WhatsNew = 'whats-new',
}
