default: &default
  key_path: /path/to/key.pem
  repo_url: https://github.com/sn-project/sn-web-client.git
  user: ssh_username

staging:
  <<: *default
  server: staging.yourdomain.com
  branch: staging
  deploy_to: ~/sn-staging-client

production:
  <<: *default
  server: yourdomain.com
  deploy_to: ~/sn-prod-client
