export enum ReactNativeToWebEvent {
  EnteringBackground = 'EnteringBackground',
  ResumingFromBackground = 'ResumingFromBackground',
  GainingFocus = 'GainingFocus',
  LosingFocus = 'LosingFocus',
  AndroidBackButtonPressed = 'AndroidBackButtonPressed',
  ColorSchemeChanged = 'ColorSchemeChanged',
  KeyboardFrameWillChange = 'KeyboardFrameWillChange',
  KeyboardFrameDidChange = 'KeyboardFrameDidChange',
  KeyboardWillShow = 'KeyboardWillShow',
  KeyboardWillHide = 'KeyboardWillHide',
  ReceivedFile = 'ReceivedFile',
  ReceivedLink = 'ReceivedLink',
  ReceivedText = 'ReceivedText',
  OpenFilePreview = 'OpenFilePreview',
}
