export const Web_TYPES = {
  Application: Symbol.for('Application'),

  // Services
  ItemGroupController: Symbol.for('ItemGroupController'),
  RouteService: Symbol.for('RouteService'),
  KeyboardService: Symbol.for('KeyboardService'),
  ArchiveManager: Symbol.for('ArchiveManager'),
  ThemeManager: Symbol.for('ThemeManager'),
  AutolockService: Symbol.for('AutolockService'),
  DesktopManager: Symbol.for('DesktopManager'),
  ViewControllerManager: Symbol.for('ViewControllerManager'),
  ChangelogService: Symbol.for('ChangelogService'),
  MomentsService: Symbol.for('MomentsService'),
  VaultDisplayService: Symbol.for('VaultDisplayService'),
  PersistenceService: Symbol.for('PersistenceService'),
  MobileWebReceiver: Symbol.for('MobileWebReceiver'),
  AndroidBackHandler: Symbol.for('AndroidBackHandler'),
  Importer: Symbol.for('Importer'),

  // Controllers
  FilePreviewModalController: Symbol.for('FilePreviewModalController'),
  QuickSettingsController: Symbol.for('QuickSettingsController'),
  VaultSelectionMenuController: Symbol.for('VaultSelectionMenuController'),
  PaneController: Symbol.for('PaneController'),
  PreferencesController: Symbol.for('PreferencesController'),
  SelectedItemsController: Symbol.for('SelectedItemsController'),
  FeaturesController: Symbol.for('FeaturesController'),
  NavigationController: Symbol.for('NavigationController'),
  NotesController: Symbol.for('NotesController'),
  SearchOptionsController: Symbol.for('SearchOptionsController'),
  LinkingController: Symbol.for('LinkingController'),
  ItemListController: Symbol.for('ItemListController'),
  NoAccountWarningController: Symbol.for('NoAccountWarningController'),
  AccountMenuController: Symbol.for('AccountMenuController'),
  SubscriptionController: Symbol.for('SubscriptionController'),
  PurchaseFlowController: Symbol.for('PurchaseFlowController'),
  FilesController: Symbol.for('FilesController'),
  HistoryModalController: Symbol.for('HistoryModalController'),
  ImportModalController: Symbol.for('ImportModalController'),
  ToastService: Symbol.for('ToastService'),
  ApplicationEventObserver: Symbol.for('ApplicationEventObserver'),
  SyncStatusController: Symbol.for('SyncStatusController'),
  ActionsMenuController: Symbol.for('ActionsMenuController'),

  // Use cases
  IsGlobalSpellcheckEnabled: Symbol.for('IsGlobalSpellcheckEnabled'),
  IsNativeMobileWeb: Symbol.for('IsNativeMobileWeb'),
  IsNativeIOS: Symbol.for('IsNativeIOS'),
  IsMobileDevice: Symbol.for('IsMobileDevice'),
  PanesForLayout: Symbol.for('PanesForLayout'),
  IsTabletOrMobileScreen: Symbol.for('IsTabletOrMobileScreen'),
  GetItemTags: Symbol.for('GetItemTags'),
  LoadPurchaseFlowUrl: Symbol.for('LoadPurchaseFlowUrl'),
  GetPurchaseFlowUrl: Symbol.for('GetPurchaseFlowUrl'),
  OpenSubscriptionDashboard: Symbol.for('OpenSubscriptionDashboard'),
}
