export const VaultTests = {
  enabled: false,
  exclusive: false,
  files: [
    'vaults/vaults.test.js',
    'vaults/pkc.test.js',
    'vaults/contacts.test.js',
    'vaults/crypto.test.js',
    'vaults/asymmetric-messages.test.js',
    'vaults/keypair-change.test.js',
    'vaults/signatures.test.js',
    'vaults/shared_vaults.test.js',
    'vaults/invites.test.js',
    'vaults/items.test.js',
    'vaults/conflicts.test.js',
    'vaults/deletion.test.js',
    'vaults/permissions.test.js',
    'vaults/key_rotation.test.js',
    'vaults/files.test.js',
  ],
}
