export enum KeyboardKey {
  Tab = 'Tab',
  Backspace = 'Backspace',
  Up = 'ArrowUp',
  Down = 'ArrowDown',
  Left = 'ArrowLeft',
  Right = 'ArrowRight',
  Enter = 'Enter',
  Escape = 'Escape',
  Home = 'Home',
  End = 'End',
  Space = ' ',
  PageUp = 'PageUp',
  PageDown = 'PageDown',
}
