name: Desktop ARM Test Build

on:
  push:
    branches:
      - fix/linux-arm64-build
  workflow_dispatch:

jobs:
  Linux-AppImage-Arm64:
    name: Linux AppImage ARM64
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/desktop
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install system dependencies (libsecret)
        run: |
          sudo apt-get update
          sudo apt-get install -y libsecret-1-dev pkg-config
      - name: Install FPM
        run: sudo gem install fpm -f

      - run: yarn install --immutable

      - name: Rebuild Electron Native Modules (default)
        run: yarn workspace @standardnotes/desktop rebuild:home-server

      - run: yarn build:desktop

      - run: echo APP_VERSION=$(node -p "require('./../web/package.json').version") >> $GITHUB_ENV

      - name: Compile for AppImage
        run: yarn run webpack --config desktop.webpack.prod.js

      - name: AppImageArm64
        env:
          npm_config_target_arch: 'arm64'
          npm_config_arch: 'arm64'
        run: |
          npx electron-rebuild -f -a arm64 -m ./app
          yarn workspace @standardnotes/desktop rebuild:keytar
          yarn workspace @standardnotes/desktop rebuild:home-server --arch arm64
          yarn run electron-builder --linux --arm64 -c.linux.target=AppImage --publish=never --c.extraMetadata.version=${{ env.APP_VERSION }}

      - name: Upload
        uses: actions/upload-artifact@v4.0.0
        with:
          name: dist-linux-appimage-arm64
          path: |
            packages/desktop/dist/*.AppImage
            packages/desktop/dist/*.yml
            packages/desktop/dist/*.yaml
