name: Prod

on:
  push:
    branches:
      - main
    paths:
      - packages/desktop/**

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn setup
      - name: Prettier
        run: yarn lint:formatting
      - name: Typescript
        run: yarn lint:types
      - name: ESLint
        run: yarn lint:eslint
