name: Deploy Docs to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - packages/docs/**

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn workspace @standardnotes/docs run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.CI_PAT_TOKEN }}
          publish_dir: ./packages/docs/build
