name: iOS Testflight

on: workflow_dispatch

jobs:
  ios:
    defaults:
      run:
        working-directory: packages/mobile
    runs-on: macos-latest
    timeout-minutes: 90
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Export version from package.json
        run:
          echo "PACKAGE_VERSION=$(grep '"version"' ../web/package.json | cut -d '"' -f 4 | cut -d "-" -f 1)" >> $GITHUB_ENV
      - name: Install dependencies
        run: yarn install --immutable && yarn install:pods
      - run: yarn build:mobile
      - name: Set ssh connection to Github
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Export Apple AppStore Connect API key
        run: echo "${{ secrets.APPSTORE_CONNECT_KEY }}" > ios/Authkey.p8
      - name: Ruby Setup for Fastlane
        uses: ruby/setup-ruby@v1
        with:
          working-directory: 'packages/mobile'
      - name: Setup fastlane
        uses: maierj/fastlane-action@v1.4.0
        env:
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
        with:
          lane: 'ios setup'
          subdirectory: 'packages/mobile'
      - name: fastlane
        uses: maierj/fastlane-action@v1.4.0
        env:
          APPLE_APP_ID: ${{ secrets.APP_APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          APPSTORE_CONNECT_KEY_ID: ${{ secrets.APPSTORE_CONNECT_KEY_ID }}
          APPSTORE_CONNECT_KEY_ISSUER_ID: ${{ secrets.APPSTORE_CONNECT_KEY_ISSUER_ID }}
          BUILD_NUMBER: ${{ github.run_number }}
          FASTLANE_PASSWORD: ${{ secrets.FASTLANE_PASSWORD }}
          FASTLANE_SESSION: ${{ secrets.FASTLANE_SESSION }}
          FASTLANE_USER: ${{ secrets.FASTLANE_USER }}
          MATCH_CERTIFICATES_URL: ${{ secrets.MATCH_CERTIFICATES_URL }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          PACKAGE_VERSION: ${{ env.PACKAGE_VERSION }}
        with:
          lane: 'ios testflight'
          subdirectory: 'packages/mobile'
