name: Components PR

on:
  pull_request:
    branches:
      - main
    paths:
      - packages/components/**

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: yarn install

      - name: Build components
        run: yarn build:components

      - name: Lint components
        run: yarn lint
        working-directory: packages/components

      - name: Test components
        run: yarn test
        working-directory: packages/components

      - name: Build all
        run: yarn build:all
      - name: Lint all
        run: yarn lint
      - name: Test all
        run: yarn test
